### ISSUE TITLE
Upgrade the prettier dependency

### ISSUE THREAD

**Issue by kunall17** [hexacta/prettier-check#3]
[Package.json](https://github.com/hexacta/prettier-check/blob/master/package.json) is using an very old version of the prettier, which should be upgraded now!

Current version: 0.21.0
[New version](https://github.com/prettier/prettier/releases/tag/1.6.1): 1.6.0

It would be ideal to pass a prettier version but it may be fine for now to upgrade the dependency :)

We use your prettier check in our travis CI and we are upgrading the prettier dependency hence it would create conflicts!

**Comment by pomber** [comment]
We probably should also move it to a [peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/#the-solution-peer-dependencies).

**Comment by pomber** [comment]
Released in version 2.0.0. Thanks!
